clients:
  wikipedia-api:
    host: api.wikimedia.org
    port:
    proto: https
    access-token: ${WIKIPEDIA_API_ACCESS_TOKEN}
  wikipedia-web:
    host: en.wikipedia.org
    port:
    proto: https
init:
  paths:
    - source: Gandalf
      target: Tetris
    - source: Albus_Dumbledore
      target: Poker
    - source: L'Avare_(film)
      target: H._P._Lovecraft
    - source: Alexandre_Dumas,_p√®re
      target: Pizza
    - source: Titanic
      target: Zoolander
    - source: China
      target: Tutankhamun's_mummy
    - source: United_States
      target: Nokia_3310
    - source: Batzorig_Vaanchig
      target: Mohamed_Bajeddoub
    - source: Flatulence_humor
      target: List_of_unsolved_problems_in_mathematics
    - source: Toilet_paper_orientation
      target: Trump_Steaks
    - source: Michael_Scott_(The_Office)
      target: Prison
    - source: Kevin_Bacon
      target: Bacon
    - source: Mexico
      target: Moustache
logging:
  include-application-name: false
  level:
    com.wikigrapher: DEBUG
    root: INFO
management:
  endpoint:
    env:
      show-values: ALWAYS
    health:
      group:
        readiness:
          include: '*'
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
server:
  forward-headers-strategy: native
  port: 8080
  ssl:
    enabled: false
spring:
  application:
    name: wikigrapher-slim
  config:
    activate:
      on-profile: default
  devtools:
    livereload:
      enabled: true
  docker:
    compose:
      enabled: true
      file: compose.spring.yml
      profiles:
        active:
          - neo4j
  main:
    banner-mode: off
  neo4j:
    authentication:
      password: ${NEO4J_PASSWORD}
      username: ${NEO4J_USERNAME}
    uri: bolt://localhost:7687
  output:
    ansi:
      enabled: ALWAYS
  thymeleaf:
    cache: false
  web:
    error:
      include-message: always
springdoc:
  api-docs:
    path: /api-docs
  cache:
    disabled: true
  packagesToScan: com.wikigrapher
  pathsToMatch: /**
  swagger-ui:
    disable-swagger-default-url: true
    doc-expansion: none
    operationsSorter: method
    path: /swagger-ui
    tagsSorter: alpha
---
server:
  port: 80
spring:
  config:
    activate:
      on-profile: docker
  devtools:
    add-properties: false
    livereload:
      enabled: false
    restart:
      enabled: false
  docker:
    compose:
      enabled: false
  neo4j:
    uri: bolt://neo4j:7687
